### ISSUE TITLE
sync 仓库找不到

### ISSUE THREAD

**Issue by Tunglies** [D-Robotics/x5-manifest#1]
```bash
~/x5-gen$ git log -1
commit a4acf1008b1a2ecbd065d626d6a93fb4738a92f7 (HEAD, m/develop, github/develop)
Author: xin03.liu <xin03.liu@horizon.cc>
Date:   Tue Oct 22 17:08:45 2024 +0800

    fix(mk_kernel.sh): Add menuconfig,use ./mk_kernel.sh menuconfig to make menuconfig
    
    Signed-off-by: xin03.liu <xin03.liu@horizon.cc>
```

找不到 `x5-hobot-audio-config`
```bash
error: Cannot checkout x5-hobot-audio-config: ManifestInvalidRevisionError: revision develop in x5-hobot-audio-config not found
error: in `sync`: revision develop in x5-hobot-audio-config not found
tunglies@ub2004:~/x5-gen$ ls
```

找不到 `x5-hobot-miniboot`
```bash
error: Cannot fetch x5-hobot-miniboot from ssh://git@github.com/D-Robotics/x5-hobot-miniboot
Fetching: 100% (2/2), done in 5.616s
error: Cannot checkout x5-hobot-audio-config: ManifestInvalidRevisionError: revision develop in x5-hobot-audio-config not found
error: in `sync`: revision develop in x5-hobot-audio-config not found
```

D-Robotics 下不存在公开 `x5-hobot-audio-config` 和  `x5-hobot-miniboot`

**Comment by Tunglies** [comment]
> ```shell
> ~/x5-gen$ git log -1
> commit a4acf1008b1a2ecbd065d626d6a93fb4738a92f7 (HEAD, m/develop, github/develop)
> Author: xin03.liu <xin03.liu@horizon.cc>
> Date:   Tue Oct 22 17:08:45 2024 +0800
> 
>     fix(mk_kernel.sh): Add menuconfig,use ./mk_kernel.sh menuconfig to make menuconfig
>     
>     Signed-off-by: xin03.liu <xin03.liu@horizon.cc>
> ```
> 
> 找不到 `x5-hobot-audio-config`
> 
> ```shell
> error: Cannot checkout x5-hobot-audio-config: ManifestInvalidRevisionError: revision develop in x5-hobot-audio-config not found
> error: in `sync`: revision develop in x5-hobot-audio-config not found
> tunglies@ub2004:~/x5-gen$ ls
> ```
> 
> 找不到 `x5-hobot-miniboot`
> 
> ```shell
> error: Cannot fetch x5-hobot-miniboot from ssh://git@github.com/D-Robotics/x5-hobot-miniboot
> Fetching: 100% (2/2), done in 5.616s
> error: Cannot checkout x5-hobot-audio-config: ManifestInvalidRevisionError: revision develop in x5-hobot-audio-config not found
> error: in `sync`: revision develop in x5-hobot-audio-config not found
> ```
> 
> D-Robotics 下不存在公开 `x5-hobot-audio-config` 和 `x5-hobot-miniboot`

@xin03liu

**Comment by YaQiang-Li** [comment]
@Tunglies Sorry， please try again.
